apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ingestion-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: axion-ingestion-service
  template:
    metadata:
      labels:
        app: axion-ingestion-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: axion-ingestion-service
          image: axionprojectregistry.azurecr.io/ingestion:latest
          ports:
            - containerPort: 8000
