apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ingestion-service
spec:
  selector:
    matchLabels:
      app: axion-ingestion-service
  template:
    metadata:
      labels:
        app: axion-ingestion-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: axion-ingestion-service
        image: axionprojectregistry.azurecr.io/ingestion:v1
        ports:
        - containerPort: 8000
